import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { getPersonaTemplate } from "./persona-templates.js";

export interface GenerateMusicAgentOptions {
  rootDir?: string;
  agentId?: string;
  agentName?: string;
  personaName?: string;
  wakeWord?: string;
  templateId?: string;
  force?: boolean;
}

export interface GeneratedFile {
  path: string;
  created: boolean;
}

export interface GenerateMusicAgentResult {
  rootDir: string;
  files: GeneratedFile[];
}

function resolveOpenClawHome(): string {
  if (process.env.OPENCLAW_HOME) {
    return resolve(process.env.OPENCLAW_HOME);
  }

  return resolve(join(homedir(), ".openclaw"));
}

function defaultAgentRoot(): string {
  return join(resolveOpenClawHome(), "agents", "music-agent");
}

function ensureDir(dirPath: string): void {
  mkdirSync(dirPath, { recursive: true });
}

function writeIfNeeded(filePath: string, content: string, force = false): boolean {
  ensureDir(dirname(filePath));
  if (!force && existsSync(filePath)) {
    return false;
  }

  writeFileSync(filePath, content, "utf8");
  return true;
}

function buildAgentJson(
  rootDir: string,
  options: Required<Pick<GenerateMusicAgentOptions, "agentId" | "agentName" | "wakeWord" | "templateId">>,
  description: string
): string {
  return JSON.stringify(
    {
      id: options.agentId,
      name: options.agentName,
      description,
      version: "0.1.0",
      entryMode: "agent-first",
      templateId: options.templateId,
      rootDir,
      personaFiles: ["AGENT.md", "PERSONA.md", "MEMORY_POLICY.md", "TRIGGERS.md"],
      memoryDir: "memory",
      downloadDir: "downloads",
      runtime: {
        panelEnabled: true,
        voiceEnabled: true
      },
      toolBindings: ["music_control"],
      wakeWord: options.wakeWord
    },
    null,
    2
  );
}

function buildAgentMd(agentName: string, role: string): string {
  return `# ${agentName}

## Identity

You are a dedicated music assistant generated by Music Skill.

## Role

${role}

## Responsibilities

- help the user play and control local music
- remember user preferences
- use favorites, downloads, and playlists as long-term context
- respond like a focused music assistant rather than a generic chatbot

## Boundaries

- stay within music-related tasks unless the host explicitly broadens scope
- prefer direct, efficient replies
- when uncertain, ask a concise clarification instead of guessing
`;
}

function buildPersonaMd(personaName: string, role: string, tone: string[], style: string[]): string {
  return `# Persona

## Name

${personaName}

## Role

${role}

## Tone

${tone.map((item) => `- ${item}`).join("\n")}

## Style

${style.map((item) => `- ${item}`).join("\n")}

## Editable Notes

You can change this file to rename the agent, change its personality, or alter how it speaks without editing TypeScript code.
`;
}

function buildMemoryPolicyMd(): string {
  return `# Memory Policy

## Remember

- explicit likes and dislikes
- frequently played artists and tracks
- repeated skips
- favorites, playlists, and download habits

## Avoid Remembering

- irrelevant non-music chatter
- private content unrelated to music use

## Use Of Memory

- bias recommendations toward positive preferences
- avoid negative preferences
- reuse the latest active scene when it improves continuity

## Retention Defaults

- preference notes: keep the most recent 50 entries per user
- behavior events: keep the most recent 200 entries per user
- recommendation window: use the most recent 20 behavior events when scoring tracks

## Why Retention Exists

- keeps the agent responsive over long-term use
- prevents old behavior noise from dominating recent taste
- avoids unbounded growth in local memory tables

## How To Adjust

You can change retention through environment variables in the runtime config:

- \`MUSIC_AGENT_PREFERENCE_MEMORY_LIMIT\`
- \`MUSIC_AGENT_BEHAVIOR_MEMORY_LIMIT\`
- \`MUSIC_AGENT_BEHAVIOR_WINDOW\`

Use larger values if you want longer memory. Use smaller values if you want the agent to react more strongly to recent habits.
`;
}

function buildTriggersMd(wakeWord: string, exampleCommands: string[]): string {
  return `# Triggers

## Wake Word

${wakeWord}

## Example Commands

${exampleCommands.map((command) => `- ${command}`).join("\n")}

## Notes

- keep wake word and trigger phrasing editable here
- future runtime can hot-reload these settings
`;
}

function buildEnvJson(wakeWord: string): string {
  return JSON.stringify(
    {
      musicLibraryDir: "",
      downloadDir: "./downloads",
      storageDriver: "sqlite",
      panelPort: 3310,
      wakeWord
    },
    null,
    2
  );
}

function buildGitkeep(): string {
  return "";
}

export function generateMusicAgent(options: GenerateMusicAgentOptions = {}): GenerateMusicAgentResult {
  const template = getPersonaTemplate(options.templateId);
  const rootDir = resolve(options.rootDir ?? defaultAgentRoot());
  const agentId = options.agentId ?? "music-agent";
  const agentName = options.agentName ?? template.agentName;
  const personaName = options.personaName ?? template.personaName;
  const wakeWord = options.wakeWord ?? template.wakeWord;
  const templateId = options.templateId ?? template.id;
  const force = options.force ?? false;

  const fileSpecs: Array<[string, string]> = [
    ["agent.json", buildAgentJson(rootDir, { agentId, agentName, wakeWord, templateId }, template.description)],
    ["AGENT.md", buildAgentMd(agentName, template.role)],
    ["PERSONA.md", buildPersonaMd(personaName, template.role, template.tone, template.style)],
    ["MEMORY_POLICY.md", buildMemoryPolicyMd()],
    ["TRIGGERS.md", buildTriggersMd(wakeWord, template.exampleCommands)],
    [join("config", "env.json"), buildEnvJson(wakeWord)],
    [join("memory", ".gitkeep"), buildGitkeep()],
    [join("downloads", ".gitkeep"), buildGitkeep()],
    [join("logs", ".gitkeep"), buildGitkeep()],
    [join("runtime", "panel", ".gitkeep"), buildGitkeep()],
    [join("runtime", "voice", ".gitkeep"), buildGitkeep()],
    [join("runtime", "tools", ".gitkeep"), buildGitkeep()]
  ];

  const files = fileSpecs.map(([relativePath, content]) => {
    const path = join(rootDir, relativePath);
    const created = writeIfNeeded(path, content, force);
    return { path, created };
  });

  return { rootDir, files };
}
